# -*- coding: utf-8 -*-
"""atividade algoritmos não mandem aúdio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vxZJBusopx7gjNLQm6ZBjZkjYs28WU5C
"""

import pandas as pd
import random
import time
import matplotlib.pyplot as plt

#Gerando um arquivo csv
pequena_100 = random.sample(range(1, 1000), 100)
media_1000 = random.sample(range(1, 10000), 1000)
grande_10000 = random.sample(range(1, 100000), 10000)
muito_grande_50000 = random.sample(range(1, 500000), 50000)

dados = pd.DataFrame({
    "pequena_100": pd.Series(pequena_100),
    "media_1000": pd.Series(media_1000),
    "grande_10000": pd.Series(grande_10000),
    "muito_grande_50000": pd.Series(muito_grande_50000)
})

dados.to_csv("dados_ordenacao.csv", index=False)
print("Arquivo 'dados_ordenacao.csv' criado com sucesso!")

#funçao merge
def merge_sort(array):
    if len(array) <= 1:
        return array
    meio = len(array) // 2
    esquerda = merge_sort(array[:meio])
    direita = merge_sort(array[meio:])
    return merge(esquerda, direita)

def merge(esquerda, direita):
    resultado = []
    i = j = 0
    while i < len(esquerda) and j < len(direita):
        if esquerda[i] < direita[j]:
            resultado.append(esquerda[i])
            i += 1
        else:
            resultado.append(direita[j])
            j += 1
    resultado.extend(esquerda[i:])
    resultado.extend(direita[j:])
    return resultado

# Lendo os Dados
dados = pd.read_csv("dados_ordenacao.csv")

#Converter em lista
listas = {
    "pequena_100": dados["pequena_100"].dropna().tolist(),
    "media_1000": dados["media_1000"].dropna().tolist(),
    "grande_10000": dados["grande_10000"].dropna().tolist(),
    "muito_grande_50000": dados["muito_grande_50000"].dropna().tolist(),
}

# medindo o tempo
tempos = {}
for nome, lista in listas.items():
    inicio = time.time()
    merge_sort(lista)
    fim = time.time()
    tempos[nome] = fim - inicio
    print(f"{nome}: {tempos[nome]:.4f} segundos")

# gerando o grafico
plt.figure(figsize=(8,5))
plt.bar(tempos.keys(), tempos.values())
plt.title("Tempo de execução do Merge Sort")
plt.ylabel("Tempo (segundos)")
plt.xlabel("Tamanho da lista")
plt.show()

from google.colab import files
files.download("dados_ordenacao.csv")